name: Go Compile

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.x
    - name: Compile
      run: go build ./...
